# Monitoring

### Importing the required the libraries

Using Avidently.ai for monitoring the Model

In [61]:
import pandas as pd
import numpy as np
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from evidently import ColumnMapping
from evidently.report import Report
from evidently.test_suite import TestSuite
from evidently.metric_preset import ClassificationPreset
from evidently.test_preset import DataQualityTestPreset
from evidently.test_preset import DataStabilityTestPreset
from evidently.metric_preset import TargetDriftPreset
from evidently.test_preset import DataDriftTestPreset
from evidently.test_preset import RegressionTestPreset
from evidently.test_preset import DataDriftTestPreset
from evidently.test_preset import NoTargetPerformanceTestPreset
from evidently.test_preset import MulticlassClassificationTestPreset
from evidently.test_preset import BinaryClassificationTopKTestPreset
from evidently.test_preset import BinaryClassificationTestPreset
print("Libraries Imported Succesfully!!")

Libraries Imported Succesfully!!

### Importing the train and test data set

In [41]:
ref_data = pd.read_csv("preprocessed_data.csv")
cur_data = pd.read_csv("test_data.csv")

In [42]:
ref_data.head()

,gender_Male,age,hypertension,heart_disease,ever_married,Residence_type,avg_glucose_level,bmi,work_type_Never_worked,work_type_Private,work_type_Self-employed,work_type_children,smoking_status_formerly_smoked,smoking_status_never_smoked,smoking_status_smokes,stroke
0,1,67.0,0,1,1,0,228.69,36.6,0,1,0,0,1,0,0,1
1,0,61.0,0,0,1,1,202.21,28.1,0,0,1,0,0,1,0,1
2,1,80.0,0,1,1,1,105.92,32.5,0,1,0,0,0,1,0,1
3,0,49.0,0,0,1,0,171.23,34.4,0,1,0,0,0,0,1,1
4,0,79.0,1,0,1,1,174.12,24.0,0,0,1,0,0,1,0,1

In [43]:
cur_data.head()

,gender_Male,age,hypertension,heart_disease,ever_married,Residence_type,avg_glucose_level,bmi,work_type_Never_worked,work_type_Private,work_type_Self-employed,work_type_children,smoking_status_formerly_smoked,smoking_status_never_smoked,smoking_status_smokes,stroke
0,1,72.0,0,1,1,1,141.72,33.0,0,1,0,0,0,0,0,1
1,0,79.0,0,0,1,0,143.15,31.5,0,1,0,0,0,1,0,1
2,1,73.0,0,1,1,0,82.94,33.8,0,1,0,0,1,0,0,1
3,1,70.0,0,0,1,0,77.14,25.1,0,0,1,0,0,0,1,1
4,1,78.0,0,0,1,0,105.47,21.6,0,0,0,0,1,0,0,1

In [44]:
ref_data['stroke'].value_counts()

0    4860
1     493
Name: stroke, dtype: int64

In [45]:
cur_data['stroke'].value_counts()

0    1511
1     289
Name: stroke, dtype: int64

In [46]:
ref_X = ref_data.drop(["stroke"], axis=1)
ref_y = ref_data["stroke"]

cur_X = cur_data.drop(["stroke"], axis=1)
cur_y = cur_data["stroke"]

In [47]:
ref_X_train, ref_X_test, ref_y_train, ref_y_test = train_test_split(ref_X, ref_y, test_size=0.4, random_state=60)

In [48]:
ref_y_test

3631    0
25      1
4929    0
1051    0
1413    0
       ..
128     1
3867    0
2446    0
5287    0
3739    0
Name: stroke, Length: 2142, dtype: int64

In [49]:
cur_X.head()

,gender_Male,age,hypertension,heart_disease,ever_married,Residence_type,avg_glucose_level,bmi,work_type_Never_worked,work_type_Private,work_type_Self-employed,work_type_children,smoking_status_formerly_smoked,smoking_status_never_smoked,smoking_status_smokes
0,1,72.0,0,1,1,1,141.72,33.0,0,1,0,0,0,0,0
1,0,79.0,0,0,1,0,143.15,31.5,0,1,0,0,0,1,0
2,1,73.0,0,1,1,0,82.94,33.8,0,1,0,0,1,0,0
3,1,70.0,0,0,1,0,77.14,25.1,0,0,1,0,0,0,1
4,1,78.0,0,0,1,0,105.47,21.6,0,0,0,0,1,0,0

In [50]:
ref_y.value_counts()

0    4860
1     493
Name: stroke, dtype: int64

In [51]:
rf = RandomForestClassifier()
rf.fit(ref_X_train.values, ref_y_train.values)

RandomForestClassifier()

In [52]:
ref_pred = rf .predict(ref_X_test)
ref_pred = pd.DataFrame(ref_pred, columns=["Prediction"])
cur_pred = rf.predict(cur_X)
cur_pred = pd.DataFrame(cur_pred, columns=["Prediction"])

C:\Users\hp\anaconda3\lib\site-packages\sklearn\base.py:413: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
C:\Users\hp\anaconda3\lib\site-packages\sklearn\base.py:413: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(

### Joining Prediction Column into the dataframe

In [53]:
# Merging on train data
ref_X_test.reset_index(inplace=True, drop=True)
ref_y_test.reset_index(inplace=True, drop=True)
ref_merged = pd.concat([ref_X_test, ref_y_test], axis=1)
ref_merged = pd.concat([ref_merged, ref_pred], axis=1)
ref_merged

,gender_Male,age,hypertension,heart_disease,ever_married,Residence_type,avg_glucose_level,bmi,work_type_Never_worked,work_type_Private,work_type_Self-employed,work_type_children,smoking_status_formerly_smoked,smoking_status_never_smoked,smoking_status_smokes,stroke,Prediction
0,0,82.0,0,0,1,1,78.00,31.3,0,0,1,0,1,0,0,0,1
1,1,80.0,0,0,1,1,104.12,23.5,0,0,1,0,0,1,0,1,0
2,0,70.0,0,0,1,1,96.82,25.0,0,0,1,0,0,1,0,0,0
3,0,51.0,0,0,0,1,116.14,20.9,0,0,0,0,0,1,0,0,0
4,1,18.0,0,0,1,1,140.52,27.4,0,1,0,0,0,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2137,1,82.0,0,0,1,0,200.59,29.0,0,0,0,0,1,0,0,1,0
2138,1,8.0,0,0,0,0,84.68,14.5,0,0,0,1,0,0,0,0,0
2139,1,73.0,0,1,1,1,70.23,28.1,0,0,0,0,0,1,0,0,0
2140,1,33.0,0,0,1,1,81.10,24.8,0,0,0,0,0,1,0,0,0
2141,0,16.0,0,0,0,0,63.63,20.0,0,1,0,0,0,0,1,0,0

In [54]:
# Merging in test data
cur_X.reset_index(inplace=True, drop=True)
cur_y.reset_index(inplace=True, drop=True)
cur_merged = pd.concat([cur_X, cur_y], axis=1)
cur_merged = pd.concat([cur_merged, cur_pred], axis=1)
cur_merged

,gender_Male,age,hypertension,heart_disease,ever_married,Residence_type,avg_glucose_level,bmi,work_type_Never_worked,work_type_Private,work_type_Self-employed,work_type_children,smoking_status_formerly_smoked,smoking_status_never_smoked,smoking_status_smokes,stroke,Prediction
0,1,72.0,0,1,1,1,141.72,33.0,0,1,0,0,0,0,0,1,0
1,0,79.0,0,0,1,0,143.15,31.5,0,1,0,0,0,1,0,1,0
2,1,73.0,0,1,1,0,82.94,33.8,0,1,0,0,1,0,0,1,0
3,1,70.0,0,0,1,0,77.14,25.1,0,0,1,0,0,0,1,1,0
4,1,78.0,0,0,1,0,105.47,21.6,0,0,0,0,1,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1795,1,21.0,0,0,0,0,99.66,35.8,0,1,0,0,0,1,0,0,0
1796,1,46.0,0,0,1,0,123.77,35.2,0,0,1,0,0,1,0,0,0
1797,1,42.0,0,0,1,0,105.89,36.9,0,0,1,0,0,0,0,0,0
1798,0,67.0,0,0,1,1,177.34,36.3,0,1,0,0,0,0,1,0,0
1799,1,82.0,0,0,1,0,94.00,36.6,0,0,1,0,0,0,0,0,0

### Using Column mapping of Avidently.ai

In [55]:
cm = ColumnMapping()
cm.target = "stroke"
cm.prediction = "Prediction"
cm.target_names = ["No stroke", "stroke"]

In [59]:
from evidently.metric_preset import DataQualityPreset
data_quality_report = Report(metrics=[
    DataQualityPreset(),
])

data_quality_report.run(reference_data=ref_merged, current_data=cur_merged)
data_quality_report.save_html("reports/dataqualityreport.html")

C:\Users\hp\anaconda3\lib\site-packages\evidently\metrics\data_integrity\dataset_missing_values_metric.py:146: FutureWarning:

elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison

In [62]:
num_target_drift_report = Report(metrics=[
    TargetDriftPreset(num_stattest='ks', cat_stattest='psi'),
])

num_target_drift_report.run(reference_data=ref_merged, current_data=cur_merged)
num_target_drift_report.save_html("reports/num_target_drift_report.html")

In [63]:
classification_performance_report = Report(metrics=[
    ClassificationPreset(),
])
classification_performance_report.run(reference_data=ref_merged, current_data=cur_merged, column_mapping = cm)
classification_performance_report.save_html("reports/classification_performance_report1.html")

In [64]:
ref_probas = pd.DataFrame(rf.predict_proba(ref_X_test))
ref_probas.columns = ["No stroke", "stroke"]
cur_probas = pd.DataFrame(rf.predict_proba(cur_X))
cur_probas.columns = ["No stroke", "stroke"]

C:\Users\hp\anaconda3\lib\site-packages\sklearn\base.py:413: UserWarning:

X has feature names, but RandomForestClassifier was fitted without feature names

C:\Users\hp\anaconda3\lib\site-packages\sklearn\base.py:413: UserWarning:

X has feature names, but RandomForestClassifier was fitted without feature names

In [75]:
ref_probas

      No stroke  stroke
0          1.00    0.00
1          1.00    0.00
2          0.79    0.21
3          0.68    0.32
4          0.99    0.01
...         ...     ...
1066       0.32    0.68
1067       0.85    0.15
1068       0.44    0.56
1069       1.00    0.00
1070       0.96    0.04

[1071 rows x 2 columns]

In [65]:
ref_probas.value_counts()

No stroke  stroke
1.00       0.00      621
0.99       0.01      195
0.98       0.02      135
0.97       0.03      115
0.96       0.04       87
                    ...
0.33       0.67        1
0.28       0.72        1
0.35       0.65        1
0.49       0.51        1
0.17       0.83        1
Length: 69, dtype: int64

In [66]:
ref_X_test.reset_index(inplace=True, drop=True)
ref_X_test['Attrition'] = ['No Stroke' if x == 0 else 'Stroke' for x in ref_y_test]
ref_merged = pd.concat([ref_X_test, ref_probas], axis = 1)

cur_X.reset_index(inplace=True, drop=True)
cur_X['Attrition'] = ['Stroke' if x == 0 else 'Stroke' for x in cur_y]
cur_merged = pd.concat([cur_X, cur_probas], axis = 1)

In [67]:
ref_merged

,gender_Male,age,hypertension,heart_disease,ever_married,Residence_type,avg_glucose_level,bmi,work_type_Never_worked,work_type_Private,work_type_Self-employed,work_type_children,smoking_status_formerly_smoked,smoking_status_never_smoked,smoking_status_smokes,Attrition,No stroke,stroke
0,0,82.0,0,0,1,1,78.00,31.3,0,0,1,0,1,0,0,No Stroke,0.38,0.62
1,1,80.0,0,0,1,1,104.12,23.5,0,0,1,0,0,1,0,Stroke,0.63,0.37
2,0,70.0,0,0,1,1,96.82,25.0,0,0,1,0,0,1,0,No Stroke,0.97,0.03
3,0,51.0,0,0,0,1,116.14,20.9,0,0,0,0,0,1,0,No Stroke,1.00,0.00
4,1,18.0,0,0,1,1,140.52,27.4,0,1,0,0,0,1,0,No Stroke,1.00,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2137,1,82.0,0,0,1,0,200.59,29.0,0,0,0,0,1,0,0,Stroke,0.76,0.24
2138,1,8.0,0,0,0,0,84.68,14.5,0,0,0,1,0,0,0,No Stroke,1.00,0.00
2139,1,73.0,0,1,1,1,70.23,28.1,0,0,0,0,0,1,0,No Stroke,0.78,0.22
2140,1,33.0,0,0,1,1,81.10,24.8,0,0,0,0,0,1,0,No Stroke,0.99,0.01
2141,0,16.0,0,0,0,0,63.63,20.0,0,1,0,0,0,0,1,No Stroke,0.97,0.03

In [68]:
cm  = ColumnMapping()
cm.target = 'Attrition'
cm.prediction = ['No stroke', 'stroke']
cm.pos_label = 'No stroke'

In [69]:
classification_performance_report = Report(metrics=[
    ClassificationPreset(),
])
classification_performance_report.run(reference_data=ref_merged, current_data=cur_merged, column_mapping = cm)
classification_performance_report.save_html("Reports/classification_performance_report2.html")

C:\Users\hp\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning:

Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.

C:\Users\hp\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning:

Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.

C:\Users\hp\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning:

Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.

C:\Users\hp\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning:

Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.

C:\Users\hp\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning:

Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.

C:\Users\hp\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning:

Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.

C:\Users\hp\anaconda3\lib\site-packages\sklearn\metrics\_ranking.py:1029: UndefinedMetricWarning:

No positive samples in y_true, true positive value should be meaningless

C:\Users\hp\anaconda3\lib\site-packages\sklearn\metrics\_ranking.py:1029: UndefinedMetricWarning:

No positive samples in y_true, true positive value should be meaningless

C:\Users\hp\anaconda3\lib\site-packages\sklearn\metrics\_ranking.py:891: UserWarning:

No positive class found in y_true, recall is set to one for all thresholds.

C:\Users\hp\anaconda3\lib\site-packages\sklearn\metrics\_ranking.py:891: UserWarning:

No positive class found in y_true, recall is set to one for all thresholds.

ValueError: At least one label specified must be in y_true

In [71]:
data_quality = TestSuite(tests=[
    DataQualityTestPreset(),
])

data_quality.run(reference_data=ref_merged, current_data=cur_merged)
data_quality.save_html("reports/data_quality.html")

In [70]:
data_drift = TestSuite(tests=[
    DataDriftTestPreset(stattest='psi'),
])

data_drift.run(reference_data=ref_merged, current_data=cur_merged)
data_drift.save_html("reports/data_drift.html")